name: Generate assets

on:
  push:
    branches: [ "enhancement/4357-automate-css-and-js-files-generation-on-deployment" ]
  pull_request:
    branches: [ "enhancement/4357-automate-css-and-js-files-generation-on-deployment" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - name: Build
      run: |
        npm ci
        npm audit fix
        npx browserslist@latest --update-db
        gulp run:build